-- 코드를 입력하세요
WITH RECURSIVE T AS (
    SELECT 0 AS HOUR
    UNION 
    SELECT HOUR + 1 FROM T WHERE HOUR < 23
)

SELECT HOUR, COUNT(DATETIME) AS COUNT
FROM T
LEFT JOIN ANIMAL_OUTS O
ON T.HOUR = HOUR(DATETIME)
GROUP BY 1